# Generated by Django 5.0 on 2023-12-07 15:28

import pong.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ft_User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('login', models.CharField(blank=True, max_length=255, null=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('last_login', models.DateTimeField(null=True)),
            ],
            managers=[
                ('objects', pong.manager.IntraOauth2UserManager()),
            ],
        ),
    ]
