# Generated by Django 5.0 on 2023-12-11 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ft_user',
            name='language_preference',
            field=models.CharField(choices=[('en', 'English'), ('id', 'Indonesian'), ('es', 'Spanish')], default='en', max_length=2),
        ),
    ]
