# Generated by Django 5.0.1 on 2024-01-04 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0004_alter_ft_user_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('request_id', models.IntegerField(primary_key=True, serialize=False)),
                ('request_status', models.BooleanField(default=False)),
                ('sender_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_friend_request', to='pong.ft_user')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver_friend_request', to='pong.ft_user')),
            ],
        ),
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('friendship_id', models.IntegerField(primary_key=True, serialize=False)),
                ('friend_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_id', to='pong.ft_user')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to='pong.ft_user')),
            ],
            options={
                'unique_together': {('user_id', 'friend_id')},
            },
        ),
    ]
