# Generated by Django 5.0.1 on 2024-01-08 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0008_friends_request_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opponent_alias', models.CharField(max_length=50)),
                ('user_score', models.IntegerField()),
                ('opponent_score', models.IntegerField()),
                ('timestamp', models.DateField()),
                ('game_result', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_user_id', to='pong.ft_user')),
            ],
        ),
    ]
