# Generated by Django 5.0.1 on 2024-01-16 08:12

import django.core.validators
import pong.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0010_alter_ft_user_session_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ft_user',
            name='image',
            field=models.FileField(blank=True, default='./static/pong/img/avatar.svg', null=True, upload_to='', validators=[pong.models.validate_file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'svg'])]),
        ),
    ]
