from .views_game import *
from .views_home import *
from .views_index import *
from .views_logout import *
from .views_profile import *
from .views_signin import *
from .views_updatename import *
from .views_tournament import *
from .views_table import *
from .views_updateAvatar import *
from .views_lang import *
from .views_update_users import *